application: agencytracks
version: 1a
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  secure: always
  upload: favicon\.ico
  
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)
  secure: always
  expiration: "10s"

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)
  secure: always
  expiration: "10s"

- url: /js/redactor/(.*)
  static_files: static/js/redactor\1
  upload: static/js/redactor(.*)
  secure: always
  expiration: "10s"

- url: /img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)
  secure: always
  expiration: "10s"

- url: /dashboard.*
  script: main.application
  secure: always
  login: required

- url: /clients.*
  script: main.application
  secure: always
  login: required

- url: /steps.*
  script: main.application
  secure: always
  login: required

- url: .*
  script: main.application
  secure: always
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe   
  version: latest
  
builtins:
#- deferred: on #task queues https://cloud.google.com/appengine/articles/deferred
- appstats: on